spring.application.name=banking-system
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:banking_system}
spring.config.import=optional:file:.env[.properties]
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
app.bootstrap.rbac.enabled=false
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=600
app.jwt.refresh-token-days=7
app.security.password-expiry-months=6
app.security.max-failed-login-attempts=5
app.security.lock-duration-minutes=30
app.security.auth-state-sync-cron=0 0 * * * *

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9090
logging.level.root=WARN
logging.level.com.vishal.bankingsystem=INFO
