spring.application.name=banking-system
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:banking_system}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
app.jwt.secret=${JWT_SECRET}
app.security.jwt-expiration-minutes=600
app.security.password-expiry-months=6
app.security.max-failed-login-attempts=5
app.security.lock-duration-minutes=30
app.security.auth-state-sync-cron=0 0 * * * *

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9090
logging.level.root=WARN
logging.level.com.vishal.bankingsystem=INFO
