spring.application.name=banking-system
spring.datasource.url=JDBC:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:banking_system}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9090
logging.level.root=WARN
logging.level.com.vishal.banking-system=INFO
