INSERT INTO permissions (name) VALUES
    ('VIEW_ACCOUNT'),
    ('CREATE_ACCOUNT'),
    ('DEPOSIT'),
    ('WITHDRAW'),
    ('TRANSFER'),
    ('APPROVE_LARGE_TRANSFER'),
    ('FREEZE_ACCOUNT'),
    ('UNFREEZE_ACCOUNT'),
    ('VIEW_TRANSACTION_HISTORY'),
    ('VIEW_AUDIT_LOGS'),
    ('CREATE_USER'),
    ('UPDATE_USER'),
    ('DELETE_USER'),
    ('ASSIGN_ROLE'),
    ('RESET_PASSWORD'),
    ('UNLOCK_ACCOUNT'),
    ('FLAG_FRAUD'),
    ('INVESTIGATE_FRAUD')
ON CONFLICT (name) DO NOTHING;

INSERT INTO roles (name) VALUES
    ('CUSTOMER'),
    ('CORPORATE_CUSTOMER'),
    ('TELLER'),
    ('BRANCH_MANAGER'),
    ('OPERATIONS_OFFICER'),
    ('SUPPORT_AGENT'),
    ('COMPLIANCE_OFFICER'),
    ('FRAUD_ANALYST'),
    ('INTERNAL_AUDITOR'),
    ('ADMIN'),
    ('SECURITY_ADMIN')
ON CONFLICT (name) DO NOTHING;
